version: "3.2"
services:
  macropad:
    build: .
    environment:
      - ASSETS_PATH=/assets
      - MESSAGE_BROKER_HOSTNAME=rabbitmq
      - MESSAGE_BROKER_PORT=5672
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - NGROK_TOKEN=$NGROK_TOKEN
    volumes:
      - /home/pi/assets:/assets
    networks:
      - rabbitmq_default
    restart: unless-stopped

networks:
  rabbitmq_default:
    external: true
