version: "3.2"
services:
  macropad:
    build: .
    environment:
      - DISCORD_TOKEN=OTc0MzUxOTE2ODExMjkyNzM5.GaFX1U.Fc-La42Eu-lnSKsUsbizMnchLlEkobs0SUmyP0
      - NGROK_TOKEN=2AQYFEyqGQ1fOU5EiiCqBNBpmN6_7wzvJZd6zL3CcPoFUdXZB
      - MESSAGE_BROKER_HOSTNAME=broker
      - MESSAGE_BROKER_PORT=5672
  broker:
    image: rabbitmq:3
    ports:
      - 5672:5672
      - 15692:15692
