version: "3.2"
services:
  macropad:
    build: .
    env_file:
      - .env
      - .tokens.env
    environment:
      - ASSETS_PATH=/assets
    volumes:
      - ./assets:/assets
    network_mode: host
    restart: unless-stopped
